#Workflow for Lint, test and deploy
name: lint, test and deploy
on: [push]
jobs:
    Lint-Job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Checkout begin!"
            - name: Get code
              uses: actions/checkout@v4
            - run: echo "Checkout complete!"
            - run: echo "Set up node"
            - uses: actions/setup-node@v4
            - run: echo "Node set up completed!"
            - run: echo "Starting lint actions"
            - run: npm ci
            - run: npm run lint
            - run: echo "lint complete"
